In [1]:
import os
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
# set option to see all data frame columns
pd.set_option('display.max_columns', None)

In [3]:
marin_clean = gpd.read_parquet("../../../../../../capstone/electrigrid/data/linked.parquet")
marin = gpd.read_parquet("../../../../../../capstone/electrigrid/data/linked_clean.parquet")

In [4]:
marin_all = gpd.read_parquet("../../../../../../capstone/electrigrid/data/linked_all.parquet")

In [5]:
pge = gpd.read_file("../../../../../../capstone/electrigrid/data/fig1sourcedata/PGE_limitsdemo.csv")

ERROR 1: PROJ: proj_create_from_database: Open of /Users/sarak/.conda/envs/electrigrid-env/share/proj failed

In [6]:
pge = pge[pge['CircuitName'] == "ALTO 1120"]

In [7]:
pge['ICL_kWphh'] = pd.to_numeric(pge['ICL_kWphh'])

In [8]:
marin.head()

,type,year,room,heat,cool,own,value,sqft_type,ID,GEOID_left,p_ID,code,area_m2,volume_m3,unit,geometry,index__right,circuit_id,FeederName,globalid,segment_id,LoadCapaci,voltage_kv,phase_cnt,limiting_m,limiting_c,ICA_Analys,lica_analy,Division,GenCapacit,GenericPVC,GenCapac_1,GenericCap,limiting_1,limiting_2,limiting_3,limiting_4,limiting_5,limiting_6,limiting_7,limiting_8,ScreenL,Publish,Last_Updat,SHAPE_Leng,length_m,dist_to_line_m,index_right,STATEFP,COUNTYFP,TRACTCE,GEOID_right,GEOIDFQ,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,units_by_tract,max_gen,total_feeder_length,perc_length,home_count_seg,home_count_circuit,perc_homes,tothh_Cpoly,DER_max_Cpoly,_hhWt,summ_hhWt,_hhWt_n,DER_remain
0,Single,1988.0,3.0,fossil,None,O,466382.0,living,4147850,06041126100,441,RR101,206.476091,1300.079704,1.0,POINT (-122.53161 37.89284),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2540,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1150,1.77,1770,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,996.304761,7130,06,041,126100,06041126100,1400000US06041126100,1261,Census Tract 1261,G5020,S,5298995,0,+37.9121527,-122.5404887,1072.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,1072.0,757.26,142.268265,461381.715468,2.806009e-04,0.000262
1,Multi,1983.0,4.0,fossil,None,O,700205.0,living,4147677,06041128200,441,RI101,62.118649,413.427196,2.0,POINT (-122.53446 37.89396),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2540,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1150,1.77,1770,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,991.651477,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,461381.715468,2.422040e-08,0.000002
2,Single,1988.0,4.0,fossil,None,O,948588.0,living,4147673,06041128200,441,RR101,246.221135,2975.878292,1.0,POINT (-122.53457 37.89444),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2540,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1150,1.77,1770,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,953.106054,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,461381.715468,2.422040e-08,0.000002
3,Single,1990.0,6.0,fossil,None,O,969884.0,living,4147690,06041128200,441,RR101,176.636562,1039.144536,2.0,POINT (-122.53496 37.89453),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2540,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1150,1.77,1770,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,965.440318,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,461381.715468,2.422040e-08,0.000002
4,Single,1990.0,3.0,fossil,None,O,1411593.0,living,4147672,06041128200,441,RR101,180.957265,1779.115009,1.0,POINT (-122.53545 37.89475),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2540,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1150,1.77,1770,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,973.958291,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,461381.715468,2.422040e-08,0.000002

In [9]:
pge['ICL_kWphh'].describe()

count    11.000000
mean      1.630889
std       0.744407
min       0.125251
25%       1.965475
50%       1.965475
75%       1.965475
max       1.965475
Name: ICL_kWphh, dtype: float64

In [10]:
marin['DER_remain'].describe()

count    4703.000000
mean        0.000175
std         0.000072
min         0.000000
25%         0.000155
50%         0.000155
75%         0.000243
max         0.000262
Name: DER_remain, dtype: float64

In [11]:
len(marin)

4703

In [12]:
marin['circuit_id'].unique()

array(['042031122'], dtype=object)

In [14]:
pge.head()

,Cpoly,CircuitName,GEOID10,ICL_kWphh,ICPVOF_kWphh,ICPV_kWphh,ICUGOF_kWphh,ICUG_kWphh,ICL_kWphh_cap,ICPVOF_kWphh_cap,ICPV_kWphh_cap,ICUGOF_kWphh_cap,ICUG_kWphh_cap,ICPVOF_e_kWphh,ICPV_e_kWphh,ICUGOF_e_kWphh,ICUG_e_kWphh,ICPVOF_e_kWphh_cap,ICPV_e_kWphh_cap,ICUGOF_e_kWphh_cap,ICUG_e_kWphh_cap,CircVolt_kV,Length_m,Length_m_ctot,ICA_pct,ResCust,Res_pct,Com_pct,Ind_pct,Agr_pct,Oth_pct,tothh_Cpoly,tothh_ctot,tothh_pct,tothh_perkm,SAIDI5yravg,urbanheat_pctl,ghi_kWhpm2day,tothh,racediversity,black_pct,asian_pct,nlxwhite_pct,latinx_pct,inc50kbelow_pct,inc150kplus_pct,medhhinc,edavgyrs,ownerocc_pct,singleunit_pct,unitsavg,medyrbuilt,hhdensity_fctr,hhdensity_hhsqkm,polexposure_pctl,polenvt_pctl,popsens_pctl,lingisolation_pctl,sb535disad,ObjectID,geometry
179,060411262002 ALTO 1120,ALTO 1120,60411262002,1.965475,0.961711218,4.810684076,0.269814501,8.078189403,1.965474826,0.961711218,4.810684076,0.269814501,8.078189403,1.754832035,5.603804893,1.062935317,8.871310219,1.754832035,5.603804893,1.062935317,8.871310219,12,9056.69225,79370.34359,0.889830508,3801,90.5431,6.55074,2.52501,0,0.38113,430.2325413,3618.616408,0.204119958,47.50437902,170.86,10.47133441,4.6559997,985,0.179301471,0.005165289,0.039772727,0.785123967,0.14411157,0.402030457,0.304568528,82014,16.11904762,0.519796954,0.378680203,17.82385787,1969,urban,890.8876997,27.55008454,36.67567829,5.597761555,16.65111318,No,180,None
180,060411261003 ALTO 1120,ALTO 1120,60411261003,0.125251,0.832358247,0.711981243,0.269814501,0.557395069,0.125250847,0.832358247,0.711981243,0.269814501,0.557395069,1.625479064,1.50510206,1.062935317,1.350515885,1.625479064,1.50510206,1.062935317,1.350515885,12,749.9010162,79370.34359,1,3801,90.5431,6.55074,2.52501,0,0.38113,32.6392037,3618.616408,0.015485377,43.52468258,170.86,12.6601169,5.088,479,0.02923844,0,0,0.97446458,0.010708402,0.229645094,0.532359081,171076,16.22764228,0.597077244,0.762004175,3.044885177,1943,urban,1446.317417,19.31273864,22.34056678,7.208433793,2.59965338,No,181,None
181,060411282003 ALTO 1120,ALTO 1120,60411282003,1.965475,0.961711218,4.810684076,0.269814501,1.49446504,1.965474826,0.961711218,4.810684076,0.269814501,1.49446504,1.754832035,5.603804893,1.062935317,2.287585856,1.754832035,5.603804893,1.062935317,2.287585856,12,3238.996811,79370.34359,0.580645161,3801,90.5431,6.55074,2.52501,0,0.38113,88.20491797,3618.616408,0.04184803,27.23217191,170.86,7.051361771,4.6559997,781,0.330484366,0.056277056,0.105339105,0.78018278,0.042809043,0.166453265,0.445582586,121875,16.38830898,0.661971831,0.903703704,1.340123457,1958,suburban,808.0348879,17.68680769,36.81636261,14.77559369,8.99880016,No,182,None
182,060411270001 ALTO 1120,ALTO 1120,60411270001,0.125251,0.832358247,0.711981243,0.269814501,0.525082311,0.125250847,0.832358247,0.711981243,0.269814501,0.525082311,1.625479064,1.50510206,1.062935317,1.318203128,1.625479064,1.50510206,1.062935317,1.318203128,12,230.1470032,79370.34359,1,3801,90.5431,6.55074,2.52501,0,0.38113,1.4419944,3618.616408,0.000684141,6.265536288,170.86,14.14003233,5.088,578,0.186188429,0,0.045527157,0.752396166,0.146964856,0.287197232,0.216262976,83750,15.5536105,0.487889273,0.604195804,2.18951049,1951,urban,1229.09125,15.03322583,21.88857705,10.04664328,18.38421544,No,183,None
183,060411250001 ALTO 1120,ALTO 1120,60411250001,1.965475,0.961711218,4.810684076,0.269814501,5.800139991,1.965474826,0.961711218,4.810684076,0.269814501,5.800139991,1.754832035,5.603804893,1.062935317,6.593260808,1.754832035,5.603804893,1.062935317,6.593260808,12,11324.65059,79370.34359,0.882352941,3801,90.5431,6.55074,2.52501,0,0.38113,197.6164756,3618.616408,0.093757359,17.45011682,170.86,6.26787713,4.6559997,572,0.221932619,0.011284722,0.057291667,0.846354167,0.047743056,0.229020979,0.527972028,166167,16.56584362,0.575174825,0.562706271,10.81270627,1976,suburban,323.3339662,26.84432974,24.38087137,12.11032827,23.27689641,No,184,None

In [15]:
marin_all.head()

,type,year,room,heat,cool,own,value,sqft_type,ID,GEOID_left,p_ID,code,area_m2,volume_m3,unit,geometry,index__right,circuit_id,FeederName,globalid,segment_id,LoadCapaci,voltage_kv,phase_cnt,limiting_m,limiting_c,ICA_Analys,lica_analy,Division,GenCapacit,GenericPVC,GenCapac_1,GenericCap,limiting_1,limiting_2,limiting_3,limiting_4,limiting_5,limiting_6,limiting_7,limiting_8,ScreenL,Publish,Last_Updat,SHAPE_Leng,length_m,dist_to_line_m,index_right,STATEFP,COUNTYFP,TRACTCE,GEOID_right,GEOIDFQ,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,units_by_tract,total_feeder_length,perc_length,home_count_seg,home_count_circuit,perc_homes,GenCapacit_kWphh,GenericPVC_kWphh,GenCapac_1_kWphh,GenericCap_kWphh,LoadCapaci_kWphh
0,Single,1988.0,3.0,fossil,None,O,466382.0,living,4147850,06041126100,441,RR101,206.476091,1300.079704,1.0,POINT (-122.53161 37.89284),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2.54,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1.15,1.77,1.77,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,996.304761,7130,06,041,126100,06041126100,1400000US06041126100,1261,Census Tract 1261,G5020,S,5298995,0,+37.9121527,-122.5404887,1072.0,219147.707288,0.00209,624.0,5706.0,10.935857,0.000198,0.000249,0.000355,0.000343,0.000618
1,Multi,1983.0,4.0,fossil,None,O,700205.0,living,4147677,06041128200,441,RI101,62.118649,413.427196,2.0,POINT (-122.53446 37.89396),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2.54,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1.15,1.77,1.77,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,991.651477,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,219147.707288,0.00209,624.0,5706.0,10.935857,0.000198,0.000249,0.000355,0.000343,0.000618
2,Single,1988.0,4.0,fossil,None,O,948588.0,living,4147673,06041128200,441,RR101,246.221135,2975.878292,1.0,POINT (-122.53457 37.89444),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2.54,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1.15,1.77,1.77,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,953.106054,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,219147.707288,0.00209,624.0,5706.0,10.935857,0.000198,0.000249,0.000355,0.000343,0.000618
3,Single,1990.0,6.0,fossil,None,O,969884.0,living,4147690,06041128200,441,RR101,176.636562,1039.144536,2.0,POINT (-122.53496 37.89453),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2.54,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1.15,1.77,1.77,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,965.440318,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,219147.707288,0.00209,624.0,5706.0,10.935857,0.000198,0.000249,0.000355,0.000343,0.000618
4,Single,1990.0,3.0,fossil,None,O,1411593.0,living,4147672,06041128200,441,RR101,180.957265,1779.115009,1.0,POINT (-122.53545 37.89475),457507,042031122,ALTO 1122,{8204819A-9694-4DED-BECF-F919F9DBD1E9},3646706,2.54,12.0,3,None,None,Feb 2025,Feb 2025,Sonoma,0.91,1.15,1.77,1.77,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,4.572011,4.579618,973.958291,7131,06,041,128200,06041128200,1400000US06041128200,1282,Census Tract 1282,G5020,S,3940700,38514,+37.8939641,-122.5498544,11.0,219147.707288,0.00209,624.0,5706.0,10.935857,0.000198,0.000249,0.000355,0.000343,0.000618

In [16]:
marin_all['LoadCapaci_kWphh'] = marin_all['LoadCapaci_kWphh'] * 100

In [17]:
marin_all['LoadCapaci_kWphh'].describe()

count    4703.000000
mean        0.046826
std         0.016195
min         0.003649
25%         0.042323
50%         0.053999
75%         0.061782
max         0.061782
Name: LoadCapaci_kWphh, dtype: float64

In [18]:
pge['ICL_kWphh'].describe()

count    11.000000
mean      1.630889
std       0.744407
min       0.125251
25%       1.965475
50%       1.965475
75%       1.965475
max       1.965475
Name: ICL_kWphh, dtype: float64

In [20]:
marin_all['gen_phh'] = marin_all['GenCapacit_kWphh'] + marin_all['LoadCapaci_kWphh']

In [24]:
marin_all['gen_phh_no_opflex'] = marin_all['GenCapac_1_kWphh'] + marin_all['LoadCapaci_kWphh']

In [21]:
marin_all['gen_phh'].describe()

count    4703.000000
mean        0.046994
std         0.016245
min         0.003649
25%         0.042521
50%         0.054196
75%         0.061980
max         0.061980
Name: gen_phh, dtype: float64

In [23]:
pge['ICUGOF_kWphh'] = pd.to_numeric(pge['ICUGOF_kWphh'])
pge['ICUGOF_kWphh'].describe()

count    11.000000
mean      0.255005
std       0.032950
min       0.188361
25%       0.269815
50%       0.269815
75%       0.269815
max       0.269815
Name: ICUGOF_kWphh, dtype: float64

In [25]:
marin_all['gen_phh_no_opflex'].describe()

count    4703.000000
mean        0.047154
std         0.016242
min         0.003703
25%         0.042678
50%         0.054354
75%         0.062137
max         0.062137
Name: gen_phh_no_opflex, dtype: float64

In [27]:
pge['ICUG_kWphh'] = pd.to_numeric(pge['ICUG_kWphh'])
pge['ICUG_kWphh'].describe()

count    11.000000
mean      3.743139
std       2.895646
min       0.525082
25%       1.203650
50%       3.667498
75%       5.800140
max       8.078189
Name: ICUG_kWphh, dtype: float64

In [28]:
pge_circuits = gpd.read_file("../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/LineDetail/LineDetail.shp").to_crs("EPSG:4326")

In [29]:
pge_circuits.head()

,FeederId,FeederName,globalid,CSV_LineSe,LoadCapaci,voltage_kv,phase_cnt,limiting_m,limiting_c,ICA_Analys,lica_analy,Division,GenCapacit,GenericPVC,GenCapac_1,GenericCap,limiting_1,limiting_2,limiting_3,limiting_4,limiting_5,limiting_6,limiting_7,limiting_8,ScreenL,Publish,Last_Updat,SHAPE_Leng,geometry
0,062541102,MERIDIAN 1102,{3F991049-BA44-489F-A403-DA79E95B5F6A},3862041,0,12.0,3,None,None,May 2024,May 2024,Sacramento,0,0,0,0,None,None,None,None,None,None,None,None,Unlikely to pass,1,2025-06-02,145.642120,"LINESTRING (-121.95921 39.12370, -121.95951 39..."
1,043302102,MONROE 2102,{65E86C65-2474-4DE9-831A-73C5C6C88469},5458148,2380,21.0,3,None,None,Feb 2025,Feb 2025,Sonoma,60,70,2440,2440,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,9.102052,"LINESTRING (-122.73809 38.48070, -122.73809 38..."
2,063172101,MADISON 2101,{26A0B689-C08B-4AE6-AAC1-341797C5AC4E},3180180,0,21.0,3,None,None,Dec 2024,Dec 2024,Sacramento,0,0,0,0,None,None,None,None,None,None,None,None,Unlikely to pass,1,2025-06-02,4.571886,"LINESTRING (-122.01719 38.69234, -122.01714 38..."
3,162701707,VIERRA 1707,{9B295D61-2151-4336-8039-C935C669DD4D},5317517,420,17.0,3,None,None,May 2025,May 2025,Stockton,0,0,0,0,None,None,None,None,None,None,None,None,Unlikely to pass,1,2025-06-02,47.831056,"LINESTRING (-121.24696 37.75509, -121.24642 37..."
4,254691101,NORCO 1101,{3E99B378-0FDD-4ABD-8D12-6FB6E3E30909},5041662,0,12.0,3,None,None,Apr 2025,Apr 2025,Kern,0,0,0,0,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,11.245946,"LINESTRING (-119.21527 35.29618, -119.21527 35..."

In [33]:
pge_airway = pge_circuits[pge_circuits['FeederName'] == 'AIRWAYS 1103']

In [31]:
fresno_all = gpd.read_parquet("../../../../../../capstone/electrigrid/data/fresno_all.parquet")

In [32]:
fresno_all.head()

,type,year,room,heat,cool,own,value,sqft_type,ID,GEOID_left,p_ID,code,area_m2,volume_m3,unit,geometry,index__right,circuit_id,FeederName,globalid,segment_id,LoadCapaci,voltage_kv,phase_cnt,limiting_m,limiting_c,ICA_Analys,lica_analy,Division,GenCapacit,GenericPVC,GenCapac_1,GenericCap,limiting_1,limiting_2,limiting_3,limiting_4,limiting_5,limiting_6,limiting_7,limiting_8,ScreenL,Publish,Last_Updat,SHAPE_Leng,length_m,dist_to_line_m,index_right,STATEFP,COUNTYFP,TRACTCE,GEOID_right,GEOIDFQ,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,units_by_tract,total_feeder_length,perc_length,home_count_seg,home_count_circuit,perc_homes,GenCapacit_kWphh,GenericPVC_kWphh,GenCapac_1_kWphh,GenericCap_kWphh,LoadCapaci_kWphh
0,Single,NaN,3.0,None,room,None,353430.0,living,1093575,06019001411,279,RR101,204.860806,1192.593629,NaN,POINT (-119.68252 36.74685),149946,252041103,AIRWAYS 1103,{09583907-45BA-4E4D-88AE-26FB5310EBA1},3601706,0.0,12.0,3,None,None,Apr 2025,Apr 2025,Fresno,0.0,0.0,0.0,0.0,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,35.85474,35.886046,987.998711,7578,06,019,001411,06019001411,1400000US06019001411,14.11,Census Tract 14.11,G5020,S,2509993,0,+36.7433674,-119.6911747,3.0,1.848880e+06,0.001941,2.0,16.0,12.5,NaN,NaN,NaN,NaN,NaN
1,Single,NaN,3.0,None,None,O,166806.0,living,1093654,06019001412,279,RR101,276.326044,1479.557578,NaN,POINT (-119.68096 36.74686),149946,252041103,AIRWAYS 1103,{09583907-45BA-4E4D-88AE-26FB5310EBA1},3601706,0.0,12.0,3,None,None,Apr 2025,Apr 2025,Fresno,0.0,0.0,0.0,0.0,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,35.85474,35.886046,992.082935,7579,06,019,001412,06019001412,1400000US06019001412,14.12,Census Tract 14.12,G5020,S,4800282,0,+36.7435859,-119.6639754,0.0,1.848880e+06,0.001941,2.0,16.0,12.5,NaN,NaN,NaN,NaN,NaN
2,Single,NaN,3.0,None,room,O,164692.0,living,1093563,06019001411,279,RR101,215.840455,905.974819,NaN,POINT (-119.68327 36.74685),149946,252041103,AIRWAYS 1103,{09583907-45BA-4E4D-88AE-26FB5310EBA1},3601706,0.0,12.0,3,None,None,Apr 2025,Apr 2025,Fresno,0.0,0.0,0.0,0.0,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,35.85474,35.886046,992.089466,7578,06,019,001411,06019001411,1400000US06019001411,14.11,Census Tract 14.11,G5020,S,2509993,0,+36.7433674,-119.6911747,3.0,1.848880e+06,0.001941,2.0,16.0,12.5,NaN,NaN,NaN,NaN,NaN
3,Single,NaN,3.0,None,room,None,216182.0,living,1093564,06019001411,279,RR101,305.747141,1468.362674,NaN,POINT (-119.68348 36.74685),149946,252041103,AIRWAYS 1103,{09583907-45BA-4E4D-88AE-26FB5310EBA1},3601706,0.0,12.0,3,None,None,Apr 2025,Apr 2025,Fresno,0.0,0.0,0.0,0.0,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,35.85474,35.886046,994.028058,7578,06,019,001411,06019001411,1400000US06019001411,14.11,Census Tract 14.11,G5020,S,2509993,0,+36.7433674,-119.6911747,3.0,1.848880e+06,0.001941,2.0,16.0,12.5,NaN,NaN,NaN,NaN,NaN
4,Single,NaN,3.0,None,None,None,348066.0,living,1093565,06019001411,279,RR101,282.378748,1651.461212,NaN,POINT (-119.68369 36.74685),149946,252041103,AIRWAYS 1103,{09583907-45BA-4E4D-88AE-26FB5310EBA1},3601706,0.0,12.0,3,None,None,Apr 2025,Apr 2025,Fresno,0.0,0.0,0.0,0.0,None,None,None,None,None,None,None,None,Likely to pass,1,2025-06-02,35.85474,35.886046,996.330406,7578,06,019,001411,06019001411,1400000US06019001411,14.11,Census Tract 14.11,G5020,S,2509993,0,+36.7433674,-119.6911747,3.0,1.848880e+06,0.001941,2.0,16.0,12.5,NaN,NaN,NaN,NaN,NaN

In [ ]:
fresno_all['gencap_opflex'] = fresno_all['GenCapacit_kWphh'] + fresno_all['